---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

ado_api_key: "a2a6e2f96a2c94a04661aacc6e394caa"
ado_login: "https://api.ado.eresearch.unimelb.edu.au/login"
ado_search: "https://api.ado.eresearch.unimelb.edu.au/analysis/textsearch/collections/mastodon"
mastodon_key: "f8-yNpSEGxPcQwwz_GxYtET3VumoGZ6KAQAH6bybICE"
masternode: 172.26.135.86    # Set manually
couchdb_password: admin
couchdb_user: admin