#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: tmp
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: mastodon-dynamic-vol-1
    vol_size: 10
  - vol_name: mastodon-dynamic-vol-2
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: curl
    description: "Security group for curl access"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  # - name: dev_web
  #   description: "Web portal security group for HTTP"
  #   protocol: tcp
  #   port_range_min: 8080
  #   port_range_max: 8080
  #   remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: mastodon-dynamic-harvester
    volumes: ["mastodon-dynamic-vol-1", "mastodon-dynamic-vol-2"]
    group: mastodon-dynamic
