#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
# Stop existing Couch DB Docker containers and remove them (if any)
- name: Stop CouchDB Docker container
  become: true
  community.docker.docker_container:
    name: couchdb_static
    state: absent

# Create new docker container for CouchDB and start container
- name: Create and start CouchDB Docker container
  become: true
  community.docker.docker_container:
    name: couchdb_static
    image: "ibmcom/couchdb3:{{ db_version }}"
    restart: true
    restart_policy: always
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ db_username }}"
      COUCHDB_PASSWORD: "{{ db_password }}"
      COUCHDB_SECRET: "{{ db_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""