#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all


# Force existing Docker containers for Mastodon Harvesters to stop and remove them
- name: Stop Mastodon Harvester Docker container
  become: true
  docker_container:
    name: mastodon_harvester-dynamic
    state: absent


# Create and start Mastodon Docker container
- name: Create and start Mastodon Docker container
  become: true
  docker_container:
    name: mastodon_harvester-dynamic
    image: comp90024a2grp01/mastodon_harvester:latest
    env:
      ADO_API_KEY: "{{ ado_api_key }}"
      ADO_LOGIN: "{{ ado_login }}"
      ADO_SEARCH: "{{ ado_search }}"
      MASTODON_KEY: "{{ mastodon_key }}"
      COUCHDB_IP: "{{ masternode }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_password }}"
    state: started
    pull: true
    recreate: true
    restart_policy: always
    restart: true


