#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

  
- hosts: couch
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  
  roles:
    - role: common
    - role: volumes
    - role: common-docker
    - role: couch-cluster

- hosts: couch:!masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  
  roles:
    - role: couch-cluster-setup



- hosts: backend
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  
  roles:
    - role: common
    - role: volumes
    - role: common-docker
    - role: backend-docker


- hosts: mastodon
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  
  roles:
    - role: common
    - role: volumes
    - role: common-docker
    - role: mastodon-docker