---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

- name: Install dependencies
  tags: always
  become: true
  ansible.builtin.pip:
    name:
      [
        "pip",
        "numpy",
        "pandas",
        "mastodon",
        "requests"
      ]
    state: latest

 # Clone source code repository
- name: Clone the code repository into home directory
  git:
    repo: "https://github.com/njkbarry/comp90024-a2.git"
    dest: ~/comp90024-a2
  become: true