---
- name: Remove existing network
  community.docker.docker_network:
    name: db_network.name
    state: absent
    force: true

- name: Create a network
  community.docker.docker_network:
    name: db_network.name
    driver: bridge
    tls: true

- name: Add a containers to a network, leaving existing containers connected
  community.docker.docker_network:
    name: db_network.name
    connected:
      - item.container_name
    appends: true
  loop: "{{ db_nodes }}"