#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

ado_api_key: "a2a6e2f96a2c94a04661aacc6e394caa"
ado_login: "https://api.ado.eresearch.unimelb.edu.au/login"
ado_search: "https://api.ado.eresearch.unimelb.edu.au/analysis/textsearch/collections/mastodon"
mastodon_key: "f8-yNpSEGxPcQwwz_GxYtET3VumoGZ6KAQAH6bybICE"
masternode: "{{ groups['couch'][0] }}"
db_username: zxcvbnm
db_password: zxcvbnm
db_cookie: a192aeb9904e6590849337933b000c99
db_version: 3.2.1