#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: tmp
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: db-1-vol-1
    vol_size: 10
  - vol_name: db-1-vol-2
    vol_size: 80
  - vol_name: db-2-vol-1
    vol_size: 10
  - vol_name: db-2-vol-2
    vol_size: 80
  - vol_name: db-3-vol-1
    vol_size: 10
  - vol_name: db-3-vol-2
    vol_size: 80
  - vol_name: mastodon-vol-1
    vol_size: 10
  - vol_name: mastodon-vol-2
    vol_size: 10
  - vol_name: backend-vol-1
    vol_size: 10
  - vol_name: backend-vol-2
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: curl
    description: "Security group for curl access"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  # - name: dev_web
  #   description: "Web portal security group for HTTP"
  #   protocol: tcp
  #   port_range_min: 8080
  #   port_range_max: 8080
  #   remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-1
    description: "Web portal security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-2
    description: "Web portal security group for totallity"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-3
    description: "Web portal security group for totallity"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: backend
    description: "front-end to back-end"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name:  db-1
    volumes: ["db-1-vol-1", "db-1-vol-2"]
    group: couch
    security_groups:
      - ssh
      - curl
      - couchdb-1
      - couchdb-2
      - couchdb-3
  - name:  db-2
    volumes: ["db-2-vol-1", "db-2-vol-2"]
    group: couch
    security_groups:
      - ssh
      - curl
      - couchdb-1
      - couchdb-2
      - couchdb-3
  - name:  db-3
    volumes: ["db-3-vol-1", "db-3-vol-2"]
    group: couch
    security_groups:
      - ssh
      - curl
      - couchdb-1
      - couchdb-2
      - couchdb-3
  - name: mastodon-harvester
    volumes: ["mastodon-vol-1", "mastodon-vol-2"]
    group: mastodon
    security_groups:
      - ssh
      - curl
  - name: backend-server
    volumes: ["backend-vol-1", "backend-vol-2"]
    group: backend
    security_groups:
      - ssh
      - curl
      - backend