#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
volumes:
  - mountpoint: /var/lib/docker
  - mountpoint: /data