#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all


# Force existing Docker containers for Mastodon Harvesters to stop and remove them
- name: Stop Backend Docker container
  become: true
  docker_container:
    name: backend-server_name
    state: absent


# Create and start Mastodon Docker container
- name: Create and start Backend Docker container
  become: true
  docker_container:
    name: backend-server_name
    image: comp90024a2grp01/backend_server:latest
    env:
      MASTERNODE: "{{ masternode }}"
      DB_USERNAME: "{{ db_password }}"
      DB_PASSWORD: "{{ db_username }}"
    ports:
      - "5000:5000"
    state: started
    pull: true
    recreate: true
    restart_policy: always
    restart: true


