#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
# Create an instance on NeCTAR
- name: Create an instance
  openstack.cloud.server:
    name: "{{ item.name }}"
    auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ instances }}"
  register: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.server.name }} has been created. IP address is {{ item['server']['addresses']['qh2-uom-internal'][0]['addr'] }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

- name: Wait for connection
  ansible.builtin.wait_for:
    host: "{{ item['server']['addresses']['qh2-uom-internal'][0]['addr'] }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item['server']['addresses']['qh2-uom-internal'][0]['addr'] }}"
    groups: "{{ item['item']['group'] }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined
