
#
- hosts: localhost
  vars:
    ansible_python_interpreter: /home/arnav/anaconda3/bin/python3
  vars_files:
    - variable/var.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: db_mastodon
  vars_files:
    - variable/couchdb_var.yaml
  gather_facts: true

  roles:
    - role: common
    - role: couch-volumes
    - role: docker
    - role: git-clone
    - role: twiter-api-key
    - role: docker-compose
    
- hosts: db_mastodon:!master
  vars_files:
    - variable/couchdb_var.yaml
  gather_facts: true

  roles:
    - role: couch-cluster

- hosts: web
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: git-clone
    - role: web-app-docker-compose
