---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

#####################################

# Now running DockerFile so configure
# python environment internally

# - name: Update pip
#   tags: always
#   become: true
#   ansible.builtin.pip:
#     name: pip
#     state: latest
    

# - name: Install python dependencies
#   tags: always
#   become: true
#   ansible.builtin.pip:
#     name:
#       - numpy
#       - pandas==1.5.3
#       - Mastodon.py==1.8.0
#       - requests==2.25.1

#####################################

# Instead pull docker iamges because AgentForwarding is
# a complicated little brat

# #  # Clone source code repository
# - name: Clone the code repository into home directory
#   git:
#     repo: "git@github.com:njkbarry/comp90024-a2.git"
#     dest: /home/ubuntu/comp90024-a2
#     # key_file: /home/ubuntu/.ssh/id_ed25519
#     accept_hostkey: true
#     ssh_opts: "-o ForwardAgent=yes"
#   become: true



# # Build Docker image for tweet harvester
# - name: Build an image from repo
#   docker_image:
#     build:
#       path: '/home/ubuntu/comp90024-a2/mastodon_harvester/'
#       pull: false
#     name: mastodon_harvester
#     tag: latest
#     source: build
#     force_source: true
#   become: true


#####################################


# Force existing Docker containers for Mastodon Harvesters to stop and remove them
- name: Stop Mastodon Harvester Docker container
  become: true
  docker_container:
    name: mastodon_harvester-server_name
    state: absent


# Create and start Mastodon Docker container
- name: Create and start Mastodon Docker container
  become: true
  docker_container:
    name: mastodon_harvester-server_name
    image: comp90024a2grp01/mastodon_harvester:v2-release
    env:
      TEST1: "post"
    state: started
    pull: true
    recreate: true
    restart_policy: always
    restart: true


