#
# In completion of Assignment 2 - COMP90024, The University of Melbourne 
#
# Cluster and Cloud Computing, Semester 1 2023 - Team 1 
# 
# Authors: 
#
#    * Mohammed Nasir - 1345586
#    * Elena Pashkina - 1141034
#    * Ellen Morwitch - 1257182
#    * Felipe Leefu Huang Lin - 1202652
#    * Nicholas Barry - 587667
#

---
# Create volumes from vars
- name: Create volume(s) on NeCTAR
  openstack.cloud.volume:
    display_name: "{{ item.vol_name }}"
    size: "{{ item.vol_size }}"
    availability_zone: "{{ availability_zone }}"
    wait: true
    timeout: 600
    state: present
  loop: "{{ volumes }}"
  register: os_vol

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  ansible.builtin.set_fact:
    os_vol_ids: "{{ os_vol_ids|default([]) + [ item.volume.id ] }}"
  loop: "{{ os_vol.results }}"

- ansible.builtin.debug:
    msg: "Volume {{ os_vol_ids }} has been created."
