---
# Stop existing Couch DB Docker containers and remove them (if any)
- name: Stop CouchDB Docker container
  become: yes
  community.docker.docker_container:
    name: couchdb
    state: absent

# Create new docker container for CouchDB and start container
- name: Create and start CouchDB Docker container
  become: yes
  community.docker.docker_container:
    name: item.container_name
    image: "ibmcom/couchdb3:{{ db_version }}"
    state: started
    recreate: true
    ports:
      - "{{ item.host_port }}:5984"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ db_username }}"
      COUCHDB_PASSWORD: "{{ db_password }}"
      COUCHDB_SECRET: "{{ db_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{ item.ip }}\""
  loop: "{{ db_nodes }}"