---
# Stop existing Couch DB Docker containers and remove them (if any)
- name: Stop CouchDB Docker container
  become: true
  community.docker.docker_container:
    name: couchdb
    state: absent

# Create new docker container for CouchDB and start container
- name: Create and start CouchDB Docker container
  become: true
  community.docker.docker_container:
    name: "{{ item.container_name }}"
    image: "ibmcom/couchdb3:{{ db_version }}"
    state: started
    recreate: true
    ports:
      # - "{{ item.host_port }}:5984"
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ db_username }}"
      COUCHDB_PASSWORD: "{{ db_password }}"
      COUCHDB_SECRET: "{{ db_cookie }}"
      # ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{ item['server']['addresses']['qh2-uom-internal'][0]['addr'] }}\""
      ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
      # ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{ item.ip }}\""
  # loop: "{{ db_nodes }}"