- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

  
- hosts: couch
  vars_files:
    - host_vars/couch.yaml
  gather_facts: true
  
  roles:
    - role: couch-common
    - role: couch-volumes
    - role: couch-docker
    - role: couch-cluster

- hosts: couch:!masternode
  vars_files:
    - host_vars/couch.yaml
  gather_facts: true
  
  roles:
    - role: couch-cluster-setup



- hosts: backend
  vars_files:
    - host_vars/couch.yaml
  gather_facts: true
  
  roles:
    - role: couch-common
    - role: couch-volumes
    - role: couch-docker
    - role: backend-docker


- hosts: mastodon
  vars_files:
    - host_vars/mastodon.yaml
  gather_facts: true
  
  roles:
    - role: couch-common
    - role: couch-volumes
    - role: couch-docker
    - role: mastodon-docker